name: Tests
on:
  push:
    branches: ['master']
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        db_gem: [sqlite3]
        ruby:
          # - 2.5
          # - 2.6
          # - 2.7
          # - 2.7
          - 3.2
          # - 3.3
          # - 3.4
        rails:
          # - 7.0
          - 7.1
          - 7.2
          - '8.0'
        include:
          # - ruby: 3.2
          #   rails: 7.2
          #   db_gem: mysql2
          - ruby: 3.2
            rails: 7.2
            db_gem: pg
          - ruby: 3.2
            rails: 8.0
            db_gem: pg
    env:
      RAILS_ENV: test
      BUNDLE_WITHOUT: lint
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/rails_${{ matrix.rails }}_${{ matrix.db_gem }}.gemfile

    services:
      mysql:
        image: ${{ (matrix.db_gem == 'mysql2' && 'mysql') || '' }} # conditional service
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        ports: ['3306:3306']
      postgres:
        image: ${{ (matrix.db_gem == 'pg' && 'postgres') || '' }} # conditional service
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test
        ports: ['5432:5432']

    steps:
    - uses: actions/checkout@v5

    - name: Install ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"
        bundler-cache: true

    - name: Set env DATABASE_URL
      run: |
        if [[ "${{ matrix.db_gem }}" == 'mysql2' ]]; then
          echo "DATABASE_URL=mysql2://root:password@127.0.0.1:3306/test" >> "$GITHUB_ENV"
        elif [[ "${{ matrix.db_gem }}" == 'pg' ]]; then
          echo "DATABASE_URL=postgres://postgres:password@localhost:5432/test" >> "$GITHUB_ENV"
        fi

    - name: Run test
      run: |
        bundle exec rake test
